### Site metadata ###

title: The Wandering Glitch
description: "Random thoughts"

email: industrial.inference@gmail.com
twitter_username: aabs
github_username: aabs

### Build settings ###

url: "https://aabs.github.io"
baseurl: "/"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap

permalink: pretty

exclude:
  - LICENSE
  - README.md
  - Makefile

  # In Jekyll 4, these are always excluded, so you never have to add them to your list.
  # But in Jekyll 3, these are needed:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
